// Mirrors src/wikipulse/events.py: the stable contract at the edge of the Wikimedia schema.
// tests/parity.test.ts checks this file against vectors generated by the Python implementation.

export class InvalidEvent extends Error {}

export interface Edit {
  eventId: string;
  wiki: string;
  pageId: number;
  revisionId: number;
  /** Unix seconds, event time as reported by Wikimedia. */
  timestamp: number;
  user: string;
  title: string;
  pageUrl: string;
  serverUrl: string;
  bot: boolean;
  comment: string;
  oldLength: number | null;
  newLength: number | null;
  schemaUri: string;
  /** Created by the demo's "try a hard case" controls, never by Wikimedia. */
  synthetic?: boolean;
}

type Json = Record<string, unknown>;

function required(obj: Json, key: string): unknown {
  if (!(key in obj) || obj[key] === undefined) throw new InvalidEvent(`missing ${key}`);
  return obj[key];
}

function integer(value: unknown, field: string): number {
  const n = typeof value === "string" && value.trim() !== "" ? Number(value) : value;
  if (typeof n !== "number" || !Number.isInteger(n)) throw new InvalidEvent(`bad ${field}`);
  return n;
}

function optionalInteger(value: unknown): number | null {
  return value === null || value === undefined ? null : integer(value, "length");
}

/** Returns null for valid non-edit or canary events; throws for malformed edit records. */
export function parseEdit(payload: string | Json): Edit | null {
  let obj: unknown;
  try {
    obj = typeof payload === "string" ? JSON.parse(payload) : payload;
  } catch (error) {
    throw new InvalidEvent(String(error));
  }
  if (!obj || typeof obj !== "object" || Array.isArray(obj)) {
    throw new InvalidEvent("expected a JSON object");
  }
  const event = obj as Json;
  const meta = (event.meta ?? {}) as Json;
  if (event.type !== "edit" || meta.domain === "canary") return null;

  const requiredMeta = required(event, "meta") as Json;
  const revision = required(event, "revision") as Json | null;
  if (!revision || typeof revision !== "object") throw new InvalidEvent("bad revision");
  const edit: Edit = {
    eventId: String(required(requiredMeta, "id")),
    wiki: String(required(event, "wiki")),
    pageId: integer(required(event, "id"), "id"),
    revisionId: integer(required(revision, "new"), "revision"),
    timestamp: integer(required(event, "timestamp"), "timestamp"),
    user: String(required(event, "user")),
    title: String(required(event, "title")),
    pageUrl: String(event.title_url ?? ""),
    serverUrl: String(event.server_url ?? ""),
    bot: Boolean(event.bot ?? false),
    comment: String(event.comment ?? ""),
    oldLength: null,
    newLength: null,
    schemaUri: String(event.$schema ?? "unknown"),
  };
  const lengths = (event.length ?? {}) as Json;
  edit.oldLength = optionalInteger(lengths.old);
  edit.newLength = optionalInteger(lengths.new);
  if (!edit.eventId || !edit.wiki || edit.pageId <= 0 || edit.revisionId <= 0 || !edit.user) {
    throw new InvalidEvent("empty or invalid identity field");
  }
  return edit;
}

export function diffUrl(edit: Edit): string | null {
  const origin = edit.serverUrl || safeOrigin(edit.pageUrl);
  return origin && !edit.synthetic ? `${origin}/w/index.php?diff=${edit.revisionId}` : null;
}

function safeOrigin(url: string): string | null {
  try {
    return new URL(url).origin;
  } catch {
    return null;
  }
}

/** Only link out to Wikimedia projects over HTTPS. */
export function safeWikiUrl(url: string | null): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url);
    const host = parsed.hostname;
    const wikimedia = [
      "wikipedia.org",
      "wikimedia.org",
      "wikidata.org",
      "wiktionary.org",
      "wikiquote.org",
      "wikibooks.org",
      "wikisource.org",
      "wikinews.org",
      "wikiversity.org",
      "wikivoyage.org",
      "mediawiki.org",
      "wikifunctions.org",
    ].some((domain) => host === domain || host.endsWith(`.${domain}`));
    return parsed.protocol === "https:" && wikimedia ? parsed.href : null;
  } catch {
    return null;
  }
}
