const STAGES = [
  ["EventStreams", "Wikimedia's public SSE feed of every change"],
  ["Producer", "Python; acks before advancing the cursor; DLQ"],
  ["Kafka", "KRaft broker; wiki.edits.raw × 3 partitions"],
  ["Spark", "Structured Streaming; 10 s microbatches"],
  ["Iceberg", "bronze · silver · alerts, keyed MERGEs"],
  ["FastAPI", "serves the snapshot written after each commit"],
];

const MAPPING = [
  ["Ingest", "EventSource from your browser; resumes with Last-Event-ID", "Producer persists the cursor only after Kafka acknowledges"],
  ["Batching", "Arrivals buffered, committed every 10 s", "processingTime = 10 s, maxOffsetsPerTrigger = 2000"],
  ["Dedupe", "Event-id set bounded by a 10-minute event-time watermark", "dropDuplicatesWithinWatermark, then MERGE on event_id"],
  ["Late data", "Older than the watermark: counted, dropped", "Dropped from silver, retained in bronze for backfill"],
  ["Rules", "TypeScript port, parity-tested against Python", "Spark SQL expressions, per-page 5-minute lookback"],
  ["Storage", "Memory, last 15 minutes", "Iceberg tables: time travel, schema evolution"],
];

export function HowItWorks() {
  return (
    <section className="essay" aria-labelledby="essay-title">
      <header className="section-head">
        <span className="kicker">How it works</span>
        <h2 id="essay-title">The page you are using is a working model of the pipeline.</h2>
      </header>

      <div className="essay-cols">
        <div className="essay-text">
          <p>
            Wikipedia publishes every change as a public event. The production path for WikiPulse is a Python
            producer that writes those events to Kafka, a Spark Structured Streaming job that turns them into
            Iceberg tables, and a small API that serves the result. That stack runs in Docker, which a portfolio
            page cannot host.
          </p>
          <p>
            So the demo runs the same decisions in your browser instead. The event contract, the review score and the
            alert rules are ported to TypeScript. A test suite replays more than 1,500 cases generated by the Python
            code, most of them real captured edits, and requires the port to agree on every one.
            <sup>1</sup> The browser engine also models the parts of streaming that are easy to describe and hard to
            picture: microbatches, an event-time watermark, and deduplication. The seismograph above draws them as they
            happen.
          </p>
          <p>
            What the browser cannot model is durability. Spark checkpoints its Kafka offsets and dedupe state, and
            Iceberg commits each table atomically, so a crash replays work without double-counting it. Reload this page
            and its state starts over.
          </p>
        </div>
        <ol className="stack-list">
          {STAGES.map(([name, detail], i) => (
            <li key={name}>
              <span className="stack-i">{String(i + 1).padStart(2, "0")}</span>
              <b>{name}</b>
              <span>{detail}</span>
            </li>
          ))}
        </ol>
      </div>

      <div className="mapping">
        <table>
          <thead>
            <tr>
              <th scope="col">Concern</th>
              <th scope="col">In this page</th>
              <th scope="col">In the Docker pipeline</th>
            </tr>
          </thead>
          <tbody>
            {MAPPING.map(([concern, browser, spark]) => (
              <tr key={concern}>
                <th scope="row">{concern}</th>
                <td>{browser}</td>
                <td>{spark}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="evidence">
        <header className="section-head small">
          <span className="kicker">On the record</span>
          <h3>Checked on the real stack: Kafka 4.0, Spark 4.0.4, Iceberg 1.10.2, 7 Oct 2026</h3>
        </header>
        <div className="evidence-grid">
          <article>
            <span className="big-num">8 → 4</span>
            <p>
              Four edits delivered twice through Kafka. Bronze recorded all eight deliveries; silver and the alerts table
              settled on four unique edits and one edit-war alert.
            </p>
          </article>
          <article>
            <span className="big-num">1 → 0</span>
            <p>
              One edit stamped an hour behind the stream reached bronze, stayed out of silver, and Spark reported
              late_rows_dropped = 1 for that batch.
            </p>
          </article>
          <article>
            <span className="big-num">700 / 700</span>
            <p>
              Messages whose partition matched crc32(key) mod 3, sampled from all three partitions of the live broker.
              The inspector's “Kafka key → partition” line uses that mapping.
            </p>
          </article>
          <article>
            <span className="big-num">20 → 45</span>
            <p>
              English Wikipedia now shows logged-out editors as temporary accounts. The first scorer only recognised IPs,
              so those edits scored 20. After the fix they score 45 and up, in Spark and here.
            </p>
          </article>
        </div>
      </div>

      <div className="limits">
        <header className="section-head small">
          <span className="kicker">Limits</span>
          <h3>What this does not claim</h3>
        </header>
        <ul>
          <li>The score orders a queue. No labelled outcomes are used yet, so there is no precision or recall to report.</li>
          <li>“Revert?” is a pattern match on the edit summary. It misses other languages and fires on honest summaries that mention reverting.</li>
          <li>Burst rules use fixed thresholds per page. A breaking-news article trips them without anything being wrong.</li>
          <li>Bronze, silver and alerts commit separately in Iceberg. They converge; they are not one atomic transaction.</li>
        </ul>
        <p className="footnote">
          <sup>1</sup> web/tests/parity.test.ts, with vectors generated by scripts/export_capture.py from src/wikipulse/events.py.
        </p>
      </div>
    </section>
  );
}
