// Vectors are generated by scripts/export_capture.py from the Python implementation
// (src/wikipulse/events.py) over fixture edge cases and real captured enwiki edits.
import { describe, expect, it } from "vitest";
import { InvalidEvent, parseEdit } from "../src/core/contract";
import { anonymousKind, revertMatch, scoreEdit } from "../src/core/score";
import vectors from "./parity.fixture.json";

type Vector = { input: Record<string, unknown>; expected: null | "invalid" | Record<string, unknown> };

function actual(input: Record<string, unknown>) {
  try {
    const edit = parseEdit(input);
    if (!edit) return null;
    return {
      eventId: edit.eventId,
      wiki: edit.wiki,
      pageId: edit.pageId,
      revisionId: edit.revisionId,
      timestamp: edit.timestamp,
      user: edit.user,
      bot: edit.bot,
      oldLength: edit.oldLength,
      newLength: edit.newLength,
      score: scoreEdit(edit).score,
      revertHint: revertMatch(edit.comment) !== null,
      anonymous: anonymousKind(edit.user) !== null,
    };
  } catch (error) {
    if (error instanceof InvalidEvent) return "invalid";
    throw error;
  }
}

describe("TypeScript contract matches the Python pipeline", () => {
  const all = vectors as Vector[];

  it("has real captured edits and edge cases", () => {
    expect(all.length).toBeGreaterThan(100);
    expect(all.some((v) => v.expected === "invalid")).toBe(true);
    expect(all.some((v) => v.expected === null)).toBe(true);
  });

  it("parses, scores and flags every vector identically", () => {
    const mismatches = all
      .map((v, i) => ({ i, want: v.expected, got: actual(v.input) }))
      .filter(({ want, got }) => JSON.stringify(want) !== JSON.stringify(got));
    expect(mismatches.slice(0, 5)).toEqual([]);
  });
});
